import { Header } from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import { headerData } from "@/config";
import { MainNav } from "@/components/Header/components/MainNav";
import { Container } from "@/components/Container";

const barlow = Barlow({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={barlow.className}>
        <Container>
          <Header>
            <MainNav items={headerData} />
          </Header>
        </Container>
        {children}
      </body>
    </html>
  );
}
